name: Test

on:
  pull_request:
  
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: swift build
        
      - name: Run tests
        run: swift test
